packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': false
  '@scarf/scarf': false
minimumReleaseAgeExclude:
  - '@hey-api/codegen-core@0.9.0'
  - '@hey-api/openapi-ts@0.98.2'
  - '@hey-api/shared@0.4.8'
  - '@supabase/auth-js@2.108.0'
  - '@supabase/functions-js@2.108.0'
  - '@supabase/postgrest-js@2.108.0'
  - '@supabase/realtime-js@2.108.0'
  - '@supabase/storage-js@2.108.0'
  - '@supabase/supabase-js@2.108.0'
