/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as SignupVerifyRouteImport } from './routes/signup/verify'
import { Route as SignupPasswordRouteImport } from './routes/signup/password'
import { Route as ForgotPasswordVerifyRouteImport } from './routes/forgot-password/verify'
import { Route as ForgotPasswordResetRouteImport } from './routes/forgot-password/reset'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedEditorTenantIdRouteImport } from './routes/_authenticated/editor.$tenantId'
import { Route as AuthenticatedDashboardTemplatesRouteImport } from './routes/_authenticated/dashboard.templates'
import { Route as AuthenticatedDashboardSubscriptionRouteImport } from './routes/_authenticated/dashboard.subscription'
import { Route as AuthenticatedDashboardSiteRouteImport } from './routes/_authenticated/dashboard.site'
import { Route as AuthenticatedDashboardDomainRouteImport } from './routes/_authenticated/dashboard.domain'
import { Route as AuthenticatedDashboardCustomizationRouteImport } from './routes/_authenticated/dashboard.customization'
import { Route as AuthenticatedDashboardAccountRouteImport } from './routes/_authenticated/dashboard.account'
import { Route as AuthenticatedAccountDeleteRouteImport } from './routes/_authenticated/account.delete'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupVerifyRoute = SignupVerifyRouteImport.update({
  id: '/signup/verify',
  path: '/signup/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupPasswordRoute = SignupPasswordRouteImport.update({
  id: '/signup/password',
  path: '/signup/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordVerifyRoute = ForgotPasswordVerifyRouteImport.update({
  id: '/forgot-password/verify',
  path: '/forgot-password/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordResetRoute = ForgotPasswordResetRouteImport.update({
  id: '/forgot-password/reset',
  path: '/forgot-password/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedEditorTenantIdRoute =
  AuthenticatedEditorTenantIdRouteImport.update({
    id: '/editor/$tenantId',
    path: '/editor/$tenantId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardTemplatesRoute =
  AuthenticatedDashboardTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSubscriptionRoute =
  AuthenticatedDashboardSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSiteRoute =
  AuthenticatedDashboardSiteRouteImport.update({
    id: '/site',
    path: '/site',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDomainRoute =
  AuthenticatedDashboardDomainRouteImport.update({
    id: '/domain',
    path: '/domain',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCustomizationRoute =
  AuthenticatedDashboardCustomizationRouteImport.update({
    id: '/customization',
    path: '/customization',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAccountRoute =
  AuthenticatedDashboardAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAccountDeleteRoute =
  AuthenticatedAccountDeleteRouteImport.update({
    id: '/account/delete',
    path: '/account/delete',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/forgot-password/reset': typeof ForgotPasswordResetRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/signup/password': typeof SignupPasswordRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/account/delete': typeof AuthenticatedAccountDeleteRoute
  '/dashboard/account': typeof AuthenticatedDashboardAccountRoute
  '/dashboard/customization': typeof AuthenticatedDashboardCustomizationRoute
  '/dashboard/domain': typeof AuthenticatedDashboardDomainRoute
  '/dashboard/site': typeof AuthenticatedDashboardSiteRoute
  '/dashboard/subscription': typeof AuthenticatedDashboardSubscriptionRoute
  '/dashboard/templates': typeof AuthenticatedDashboardTemplatesRoute
  '/editor/$tenantId': typeof AuthenticatedEditorTenantIdRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/forgot-password/reset': typeof ForgotPasswordResetRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/signup/password': typeof SignupPasswordRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/signup': typeof SignupIndexRoute
  '/account/delete': typeof AuthenticatedAccountDeleteRoute
  '/dashboard/account': typeof AuthenticatedDashboardAccountRoute
  '/dashboard/customization': typeof AuthenticatedDashboardCustomizationRoute
  '/dashboard/domain': typeof AuthenticatedDashboardDomainRoute
  '/dashboard/site': typeof AuthenticatedDashboardSiteRoute
  '/dashboard/subscription': typeof AuthenticatedDashboardSubscriptionRoute
  '/dashboard/templates': typeof AuthenticatedDashboardTemplatesRoute
  '/editor/$tenantId': typeof AuthenticatedEditorTenantIdRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/forgot-password/reset': typeof ForgotPasswordResetRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/signup/password': typeof SignupPasswordRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/_authenticated/account/delete': typeof AuthenticatedAccountDeleteRoute
  '/_authenticated/dashboard/account': typeof AuthenticatedDashboardAccountRoute
  '/_authenticated/dashboard/customization': typeof AuthenticatedDashboardCustomizationRoute
  '/_authenticated/dashboard/domain': typeof AuthenticatedDashboardDomainRoute
  '/_authenticated/dashboard/site': typeof AuthenticatedDashboardSiteRoute
  '/_authenticated/dashboard/subscription': typeof AuthenticatedDashboardSubscriptionRoute
  '/_authenticated/dashboard/templates': typeof AuthenticatedDashboardTemplatesRoute
  '/_authenticated/editor/$tenantId': typeof AuthenticatedEditorTenantIdRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/forgot-password/reset'
    | '/forgot-password/verify'
    | '/signup/password'
    | '/signup/verify'
    | '/forgot-password/'
    | '/signup/'
    | '/account/delete'
    | '/dashboard/account'
    | '/dashboard/customization'
    | '/dashboard/domain'
    | '/dashboard/site'
    | '/dashboard/subscription'
    | '/dashboard/templates'
    | '/editor/$tenantId'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/forgot-password/reset'
    | '/forgot-password/verify'
    | '/signup/password'
    | '/signup/verify'
    | '/forgot-password'
    | '/signup'
    | '/account/delete'
    | '/dashboard/account'
    | '/dashboard/customization'
    | '/dashboard/domain'
    | '/dashboard/site'
    | '/dashboard/subscription'
    | '/dashboard/templates'
    | '/editor/$tenantId'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/forgot-password/reset'
    | '/forgot-password/verify'
    | '/signup/password'
    | '/signup/verify'
    | '/forgot-password/'
    | '/signup/'
    | '/_authenticated/account/delete'
    | '/_authenticated/dashboard/account'
    | '/_authenticated/dashboard/customization'
    | '/_authenticated/dashboard/domain'
    | '/_authenticated/dashboard/site'
    | '/_authenticated/dashboard/subscription'
    | '/_authenticated/dashboard/templates'
    | '/_authenticated/editor/$tenantId'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ForgotPasswordResetRoute: typeof ForgotPasswordResetRoute
  ForgotPasswordVerifyRoute: typeof ForgotPasswordVerifyRoute
  SignupPasswordRoute: typeof SignupPasswordRoute
  SignupVerifyRoute: typeof SignupVerifyRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/verify': {
      id: '/signup/verify'
      path: '/signup/verify'
      fullPath: '/signup/verify'
      preLoaderRoute: typeof SignupVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/password': {
      id: '/signup/password'
      path: '/signup/password'
      fullPath: '/signup/password'
      preLoaderRoute: typeof SignupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/verify': {
      id: '/forgot-password/verify'
      path: '/forgot-password/verify'
      fullPath: '/forgot-password/verify'
      preLoaderRoute: typeof ForgotPasswordVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/reset': {
      id: '/forgot-password/reset'
      path: '/forgot-password/reset'
      fullPath: '/forgot-password/reset'
      preLoaderRoute: typeof ForgotPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/editor/$tenantId': {
      id: '/_authenticated/editor/$tenantId'
      path: '/editor/$tenantId'
      fullPath: '/editor/$tenantId'
      preLoaderRoute: typeof AuthenticatedEditorTenantIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/templates': {
      id: '/_authenticated/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof AuthenticatedDashboardTemplatesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/subscription': {
      id: '/_authenticated/dashboard/subscription'
      path: '/subscription'
      fullPath: '/dashboard/subscription'
      preLoaderRoute: typeof AuthenticatedDashboardSubscriptionRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/site': {
      id: '/_authenticated/dashboard/site'
      path: '/site'
      fullPath: '/dashboard/site'
      preLoaderRoute: typeof AuthenticatedDashboardSiteRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/domain': {
      id: '/_authenticated/dashboard/domain'
      path: '/domain'
      fullPath: '/dashboard/domain'
      preLoaderRoute: typeof AuthenticatedDashboardDomainRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/customization': {
      id: '/_authenticated/dashboard/customization'
      path: '/customization'
      fullPath: '/dashboard/customization'
      preLoaderRoute: typeof AuthenticatedDashboardCustomizationRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/account': {
      id: '/_authenticated/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof AuthenticatedDashboardAccountRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/account/delete': {
      id: '/_authenticated/account/delete'
      path: '/account/delete'
      fullPath: '/account/delete'
      preLoaderRoute: typeof AuthenticatedAccountDeleteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAccountRoute: typeof AuthenticatedDashboardAccountRoute
  AuthenticatedDashboardCustomizationRoute: typeof AuthenticatedDashboardCustomizationRoute
  AuthenticatedDashboardDomainRoute: typeof AuthenticatedDashboardDomainRoute
  AuthenticatedDashboardSiteRoute: typeof AuthenticatedDashboardSiteRoute
  AuthenticatedDashboardSubscriptionRoute: typeof AuthenticatedDashboardSubscriptionRoute
  AuthenticatedDashboardTemplatesRoute: typeof AuthenticatedDashboardTemplatesRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAccountRoute: AuthenticatedDashboardAccountRoute,
    AuthenticatedDashboardCustomizationRoute:
      AuthenticatedDashboardCustomizationRoute,
    AuthenticatedDashboardDomainRoute: AuthenticatedDashboardDomainRoute,
    AuthenticatedDashboardSiteRoute: AuthenticatedDashboardSiteRoute,
    AuthenticatedDashboardSubscriptionRoute:
      AuthenticatedDashboardSubscriptionRoute,
    AuthenticatedDashboardTemplatesRoute: AuthenticatedDashboardTemplatesRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedAccountDeleteRoute: typeof AuthenticatedAccountDeleteRoute
  AuthenticatedEditorTenantIdRoute: typeof AuthenticatedEditorTenantIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedAccountDeleteRoute: AuthenticatedAccountDeleteRoute,
  AuthenticatedEditorTenantIdRoute: AuthenticatedEditorTenantIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ForgotPasswordResetRoute: ForgotPasswordResetRoute,
  ForgotPasswordVerifyRoute: ForgotPasswordVerifyRoute,
  SignupPasswordRoute: SignupPasswordRoute,
  SignupVerifyRoute: SignupVerifyRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
