import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsObject, IsString } from 'class-validator';

export class PublishSiteDto {
  /** The GrapesJS project JSON (editor state) at publish time. */
  @ApiProperty({ type: 'object', additionalProperties: true })
  @IsObject()
  project!: Record<string, unknown>;

  /** HTML generated by the `studio:projectFiles` command. */
  @ApiProperty()
  @IsString()
  @IsNotEmpty()
  exportedHtml!: string;
}
